### ISSUE TITLE
Indent file

### ISSUE THREAD

**Issue by x37v** [vim-jp/vim-cpp#12]
vim indenting is very poor for c++ lambdas, if someone has an indent file to share that resolves that, that would be great!

**Comment by crazymaster** [comment]
This repository doesn't contains indent/cpp.vim. So please report it to vim-dev.

**Comment by crazymaster** [comment]
Oops, it was reported to vim-dev.
https://groups.google.com/d/topic/vim_dev/Hr_vGp_-JxM/discussion
https://groups.google.com/d/topic/vim_dev/IAnQft51UEY/discussion
