### ISSUE TITLE
Last "merge master" removed c++11 keywords

### ISSUE THREAD

**Issue by oblitum** [vim-jp/vim-cpp#15]
The last "merge master" was to fix a previous sync, that erased the previous raw string literals support. It has fixed that but has erased other c++11 keywords and constants that were added previously. Any reason for that?

**Comment by crazymaster** [comment]
@mattn You doesn't seem to send the patch (the part of https://github.com/vim-jp/vim-cpp/commit/09f3b23458d501a39286269a18d74ec798cc6d13).
https://groups.google.com/d/topic/vim_dev/CSVKWlZvNEc/discussion

**Comment by mattn** [comment]
Whoa. WTF. Sorry...

I'll make a patch to send in later.

**Comment by mattn** [comment]
https://gist.github.com/mattn/8e876fa307096f9a7f9b

https://groups.google.com/forum/#!topic/vim_dev/MszvcBd8p1Q

done

**Comment by crazymaster** [comment]
>https://groups.google.com/forum/#!topic/vim_dev/MszvcBd8p1Q
>
>https://gist.githubusercontent.com/mattn/8e876fa307096f9a7f9b/raw/bed952ad3dc55d054b92ddef2c344bf48a396226/gistfile1.diff
The link of the post is outdated.
You should send new link.

**Comment by mattn** [comment]
done

**Comment by crazymaster** [comment]
https://github.com/vim-jp/vim/commit/d24ef06a8ae7ed2bb6d03a3d02eaa00cf961b3e8#diff-c76b7dafa87216bb9281fb15dcc2321e

**Comment by mattn** [comment]
:v:
