### ISSUE TITLE
send patch 2014/05/23

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-cpp#24]
* https://github.com/vim-jp/cpp-vim/commit/eda6bcbfbac1e09ab692069342d4846f838786d2

**Comment by crazymaster** [comment]
ping

**Comment by crazymaster** [comment]
patch送る前にupstreamの変更を取り込まないといけませんね

**Comment by mattn** [comment]
一旦 master をオフィシャル配布物にしました。

* developで開発し
* 取り込まれたらmasterにマージ
という方針にしたいと思います。

**Comment by crazymaster** [comment]
masterをdevelop相当にして
upstreamを生やすのはどうでしょうか？

**Comment by mattn** [comment]
Bram がこっちに依頼無しに変更するので運用が崩壊してる。まずい。

**Comment by mattn** [comment]
あとちょっとでマージ出来ます。つらい。

**Comment by h-east** [comment]
がんばれ～

**Comment by crazymaster** [comment]
>masterをdevelop相当にして
upstreamを生やすのはどうでしょうか？

プラグインマネージャーはデフォルトでmasterブランチを参照するので、
開発版を使いたい人は普通にインストールすればよいので楽だと思います。

**Comment by mattn** [comment]
じゃぁ逆にしましょうか。

**Comment by mattn** [comment]
マージ完了。疲れた。
差分多かったけど機能的にマージしたら凄い少ない！

**Comment by mattn** [comment]
今後こうならない為にも今すぐ出しちゃいます。

**Comment by mattn** [comment]
done

**Comment by crazymaster** [comment]
ここらへんの要らないブランチ削除しても大丈夫です？
* develop_
* fix_nested_lambda
* merge_bram_changes
* cpp_doxygen

**Comment by mattn** [comment]
おねがいしまーす

On Sun, Mar 1, 2015 at 2:51 AM, master <notifications@github.com> wrote:

> ここらへんの要らないブランチ削除しても大丈夫です？
>
>    - develop_
>    - fix_nested_lambda
>    - merge_bram_changes
>    - cpp_doxygen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vim-jp/vim-cpp/issues/24#issuecomment-76536960>.
>



-- 
- Yasuhiro Matsumoto
