### ISSUE TITLE
Autoindenting still happens in raw string literals

### ISSUE THREAD

**Issue by MarkLodato** [vim-jp/vim-cpp#28]
When writing a raw string literal, the autoindent still tries to indent labels (whenever you type a colon) or directives (whenever you type # at the start of a line).  For example, suppose you intend to type the following:

```c++
const char* s = R"(
    test {
      bar {
        # comment
        field: 123
      }
    }
    )";
```

Vim will move the `#comment` and `field:` to the leftmost column because it thinks they are preprocessor directives and labels, respectively.

**Comment by mattn** [comment]
This repository doesn't contains indent/cpp.vim. So please report it to vim-dev.

**Comment by MarkLodato** [comment]
Ah, thanks.  [Reported](https://groups.google.com/d/msg/vim_dev/6lETh3ycCbA/VZGgIfe0MCsJ).
