### ISSUE TITLE
C の #define 文で 0 が現れるとハイライトが壊れる

### ISSUE THREAD

**Issue by 0xBADDCAFE** [vim-jp/vim-cpp#29]
https://github.com/vim-jp/issues/issues/667 より移管します。

- - -

魔窟 `c.vim` で発見されました。

```
Date:   Thu Oct 2 01:41:41 2014 +0200

    Update runtime files.
```
の際の変更で入ったようです。

```c
#define TEST_0 "foobar"
```

のような、`#define` 以降に 0 が現れる構文で 0 以降がコメントアウト色となります。

c.vim 64 行目

```VimL
syn region	cCppOut2	contained start="0" end="^\s*\(%:\|#\)\s*\(endif\>\|else\>\|elif\>\)" contains=cSpaceError,cCppSkip
```

で start が 0 になっているからのようですが、どのように修正するのが適切か分かりません。
`#if 0` 構文に絡むようなので `if\s\+0` とかしてしまってもいいものでしょうか。

**Comment by crazymaster** [comment]
Closeable?

**Comment by mattn** [comment]
治っている様なので閉じます。

**Comment by 0xBADDCAFE** [comment]
反応遅れてすいません。closeable でした。ありがとうございます。
